language: node_js
node_js:
- '8'
script:
- echo 'Build starts!!'
- echo 'Installing Deps!'
- yarn
- echo 'Building'
- yarn build
addons:
  ssh_known_hosts: zsiri.eu
before_deploy:
- openssl aes-256-cbc -K $encrypted_43d342d06210_key -iv $encrypted_43d342d06210_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_rsa
- ssh-add ./deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build/* git@zsiri.eu:/var/www/condorcet-server
  on:
    branch: master
after_deploy:
- ssh -i ./deploy_rsa git@zsiri.eu "forever start /var/www/condorcet-server/index.js"
after_success:
- codecov -f coverage/*.json
